feat: update dependencies and refactor project dependencies management
1Hive/1hive-ui pull request #29
Opened 2022-01-10 06:32 UTC by reznord

As I have mentioned in https://github.com/1Hive/gardens-ui/issues/785, the current 1hive-ui library ships a bunch of libraries which are really not necessary to be shipped along with the component library.

This is an attempt in reducing the foot-print of the library by moving the dependencies to peerDependencies.

In this PR, the following things needs to be done:

- [ ]  Update all the dependencies of 1hive-ui library
- [ ] Move react-spring, dayjs to peerDependencies
- [ ] Add Changelog to the repo with the decisions

### Note: 
This should be a major release since we are moving a few libs to `peerDependencies` from `dependencies`.

2022-03-21 17:21 UTC, 0xGabi commented
@reznord is this one ready to review?

>Should I update these dependencies in the same PR or should I update them in a separate one?

What do you think of deciding depending on the size of the PR and how extra work would be for you to split them?

2022-03-25 17:01 UTC, reznord commented
@0xGabi once I am done with the changes on the [`react-spring` library update PR](#32), then we can merge this one and release a new major version :) 

> What do you think of deciding depending on the size of the PR and how extra work would be for you to split them?

I am already doing that in a separate PR (using this as the base branch), so it will be one single PR to the end to merge.

2022-04-14 18:07 UTC, 0xGabi approved these changes
One step closer to the next.js migration 🙌

Amazing work! 🔥🚒

2022-04-14 18:07 UTC, kanaagawa commented on src/components/Popover/Popover.js
> +    console.log(this.props.opener)
Let's remember to remove this log.

2022-04-14 23:36 UTC, reznord commented on src/components/Popover/Popover.js
> +    console.log(this.props.opener)
ah yes, forgot that. Will remove it :)

2022-04-21 04:35 UTC, kamikazebr commented on devbox/apps/AppBarTabs.js
> +  console.log('tab', tab)
```suggestion
```

2022-04-21 04:41 UTC, kamikazebr requested changes
Awesome!
I left a suggestion.

2022-04-21 22:50 UTC, 0xGabi approved these changes

2022-04-21 22:51 UTC, merged